# Configuration file for Calamares
# Zyphor OS 3 "Bethany" LTS
# Syntax is YAML 1.2
---

modules-search:
  - local
  - /usr/lib/x86_64-linux-gnu/calamares

instances:
  - id: zyphor-finish-install
    module: shellprocess
    config: zyphor-finish-install.conf

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

quit-at-end: false


sequence:

# Phase 1 - prepare.
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary


# Phase 2 - install.
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - grubcfg
  - bootloader
  - plymouthcfg
  # Zyphor-specific final installation configuration
  - shellprocess@zyphor-finish-install
  - packages
  - initramfscfg
  - initramfs

  - umount


# Phase 3 - postinstall.
- show:
  - finished


# Zyphor OS branding
branding: zyphor

prompt-install: false

# Normal operating-system installation
dont-chroot: false